# "https://{default}/":
#     type: upstream
#     upstream: "app:http"
#     tls:
#         min_version: TLSv1.2
#         strict_transport_security:
#             enabled: true
#             include_subdomains: true
#             preload: true

# "https://www.{default}/":
#     type: redirect
#     to: "https://{default}/"
    
saveCookie:
    path: /saveCookie
    controller: App\Controller\MainController::saveCookie
    methods: POST

loadCookie:
    path: /loadCookie
    controller: App\Controller\MainController::loadCookie
    methods: POST

index:
    path: /
    controller: App\Controller\MainController::index

moncv:
    path: /monCV
    controller: App\Controller\CVController::index

uploadCV:
    path: /uploadCV
    controller: App\Controller\CVController::uploadCV
    
hashtag:
    path: /HashtagLive
    controller: App\Controller\HashtagController::index
    
timer:
    path: /Timer
    controller: App\Controller\TimerController::index

tbm:
    path: /TBM
    controller: App\Controller\TBMController::index

PixelClicker:
    path: /PixelClicker
    controller: App\Controller\PixelClickerController::index

CashClicker:
    path: /CashClicker
    controller: App\Controller\PixelClickerController::indexCash

PixelAdventure:
    path: /PixelAdventure
    controller: App\Controller\PixelClickerController::PixelAdventure

APIFood:
    path: /APIFood
    controller: App\Controller\APIFoodController::index
    
httphashtag:
    path: /HttpHashtagLive
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: "http://nicolasdiot.ddns.net/HashtagLive"
        permanent: true

app_logout:
    path: /logout
    methods: GET

drupal:
    path: /drupal
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: "https://nicolasdiot.ddns.net:446"
        permanent: true

angular:
    path: /angular
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: "/dist/angular/index.html"
        permanent: true
        
movierama_index:
    path: /Movierama
    controller: App\Controller\MovieramaController::index

movierama_search:
    path: /Movierama/search
    controller: App\Controller\MovieramaController::search
        
movierama_crud_index:
    path: /Movierama/index
    controller: App\Controller\MovieramaCRUDController::index

contraire:
    path: /contraire/index
    controller: App\Controller\ContraireController::index

demineur:
    path: /demineur
    controller: App\Controller\DemineurController::index

note:
    path: /note
    controller: App\Controller\NoteController::index

createNote:
    path: /note/create
    controller: App\Controller\NoteController::create

updateNote:
    path: /note/update
    controller: App\Controller\NoteController::update

deleteNote:
    path: /note/delete
    controller: App\Controller\NoteController::delete

showNote:
    path: /note/show
    controller: App\Controller\NoteController::show
    methods: POST